### ISSUE TITLE
Incorporate into sabre/event

### ISSUE THREAD

**Issue by staabm** [psalm/sabre-event-psalm-plugin#1]
Would this plugin be obsolete when we use the phpdocs and move them directly into sabre/event?

**Comment by muglug** [comment]
Yes!

**Comment by evert** [comment]
Didn't know this plugin existed. Neat AF

**Comment by staabm** [comment]
Wasnt aware either. Just found it by chance today :)

**Comment by staabm** [comment]
Just added the types and prepared a new release
